name: Graceful Insights
favicon: null
layout_spectrum: 0.5942641897127032
typography_spectrum: 0.38958303071558475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5219409221317619
  lightness: 0.872339014429599
  saturation: 0.9187226463109255
  rhythmicContrast: 0.5015118937008083
purpose: []
